[versions]

kotlin = "2.0.20"
agp = "8.6.0-alpha07"
kotlinxDatetime = "0.6.0"
testng = "7.1.0"
junitKtx = "1.2.1"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }
junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }


[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
